apiVersion: v1
kind: Service
metadata:
  name: iis
spec:
  selector:
    app: iis
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 9376
  externalIPs:
    - 192.168.218.40
