apiVersion: v1
kind: Service
metadata:
  name: iis-ei
  labels:
    app: iis-ei
spec:
  selector:
    app: iis-ei
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 9376
  externalIPs:
    - 192.168.218.41
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: iis-ei
  name: iis-ei
spec:
  replicas: 2
  selector:
    matchLabels:
      app: iis-ei
  template:
    metadata:
      labels:
        app: iis-ei
      name: iis-ei
    spec:
     containers:
      - name: iis-ei
        image: mcr.microsoft.com/dotnet/samples:aspnetapp
     nodeSelector:
      kubernetes.io/os: windows
