apiVersion: v1
kind: Service
metadata:
  name: iis
spec:
  selector:
    app: iis
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 9376
  externalIPs:
    - 192.168.218.40

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: iis
  name: iis
spec:
  replicas: 2
  selector:
    matchLabels:
      app: iis
  template:
    metadata:
      labels:
      	app: iis
      name: iis
    spec:
     containers:
      - name: iis
        image: mcr.microsoft.com/dotnet/samples:aspnetapp
     nodeSelector:
      kubernetes.io/os: windows
