apiVersion: v1
kind: Service
metadata:
  name: iis
  labels:
    app: iis
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: iis
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: iis
spec:
  selector:
    matchLabels:
      run: iis
  replicas: 2
  template:
    metadata:
      labels:
        run: iis
    spec:
      containers:
      - name: iis
        image: leandroscar/iis-windows-ltsc2019
        ports:
        - containerPort: 80
     nodeSelector:
      kubernetes.io/os: windows

